/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cajero.vista;

import com.cajero.controlador.Controlador;
import javax.swing.JOptionPane;

/**
 *
 * @author David
 */
public class InterfazCajero extends javax.swing.JFrame {

    Controlador objControlador = new Controlador();

    /**
     * Creates new form InterfazCajero
     */
    public InterfazCajero() {
        initComponents();
        conexionBD();
        setLocationRelativeTo(null);
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etImagenInsertar = new javax.swing.JLabel();
        bTarjeta = new javax.swing.JButton();
        bCancelar = new javax.swing.JButton();
        bBorrar = new javax.swing.JButton();
        etInsertarBilletes = new javax.swing.JLabel();
        bAceptar = new javax.swing.JButton();
        bUno = new javax.swing.JButton();
        bDos = new javax.swing.JButton();
        bTres = new javax.swing.JButton();
        bCuatro = new javax.swing.JButton();
        bSiete = new javax.swing.JButton();
        bCinco = new javax.swing.JButton();
        bSeis = new javax.swing.JButton();
        bOcho = new javax.swing.JButton();
        bCero = new javax.swing.JButton();
        bNueve = new javax.swing.JButton();
        jTxtDinero = new javax.swing.JTextField();
        lblIntr = new javax.swing.JLabel();
        btIntroducir = new javax.swing.JButton();
        btRetirar = new javax.swing.JButton();
        btSaldo = new javax.swing.JButton();
        btTransferencia = new javax.swing.JButton();
        jTextMostrarSaldo = new javax.swing.JTextField();
        btDarseBaja = new javax.swing.JButton();
        lbIntroducir = new javax.swing.JLabel();
        lblRetirar = new javax.swing.JLabel();
        lblSaldo = new javax.swing.JLabel();
        lblTrans = new javax.swing.JLabel();
        lblBaja = new javax.swing.JLabel();
        lblSal = new javax.swing.JLabel();
        lblDestino = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        etImagenInsertar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cajero/images/imagenInsertar.png"))); // NOI18N

        bTarjeta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cajero/images/imagenTarjeta.png"))); // NOI18N
        bTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTarjetaActionPerformed(evt);
            }
        });

        bCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cajero/images/botonCancelar.png"))); // NOI18N
        bCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarActionPerformed(evt);
            }
        });

        bBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cajero/images/botonBorrar.png"))); // NOI18N
        bBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBorrarActionPerformed(evt);
            }
        });

        etInsertarBilletes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cajero/images/imagenBilletes.png"))); // NOI18N

        bAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cajero/images/botonAceptar.png"))); // NOI18N
        bAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAceptarActionPerformed(evt);
            }
        });

        bUno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cajero/images/unoBoton.png"))); // NOI18N
        bUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUnoActionPerformed(evt);
            }
        });

        bDos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cajero/images/dosBoton.png"))); // NOI18N
        bDos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDosActionPerformed(evt);
            }
        });

        bTres.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cajero/images/tresBoton.png"))); // NOI18N
        bTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTresActionPerformed(evt);
            }
        });

        bCuatro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cajero/images/cuatroBoton.png"))); // NOI18N
        bCuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCuatroActionPerformed(evt);
            }
        });

        bSiete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cajero/images/sieteBoton.png"))); // NOI18N
        bSiete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSieteActionPerformed(evt);
            }
        });

        bCinco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cajero/images/cincoBoton.png"))); // NOI18N
        bCinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCincoActionPerformed(evt);
            }
        });

        bSeis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cajero/images/seisBoton.png"))); // NOI18N
        bSeis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSeisActionPerformed(evt);
            }
        });

        bOcho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cajero/images/ochoBoton.png"))); // NOI18N
        bOcho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOchoActionPerformed(evt);
            }
        });

        bCero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cajero/images/ceroBoton.png"))); // NOI18N
        bCero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCeroActionPerformed(evt);
            }
        });

        bNueve.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cajero/images/nueveBoton.png"))); // NOI18N
        bNueve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNueveActionPerformed(evt);
            }
        });

        jTxtDinero.setEditable(false);

        lblIntr.setText("Inserta la cantidad:");

        btIntroducir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cajero/images/botonTriangular.png"))); // NOI18N
        btIntroducir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIntroducirActionPerformed(evt);
            }
        });

        btRetirar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cajero/images/botonTriangular.png"))); // NOI18N
        btRetirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRetirarActionPerformed(evt);
            }
        });

        btSaldo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cajero/images/botonTriangular.png"))); // NOI18N
        btSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSaldoActionPerformed(evt);
            }
        });

        btTransferencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cajero/images/botonTriangular.png"))); // NOI18N
        btTransferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTransferenciaActionPerformed(evt);
            }
        });

        jTextMostrarSaldo.setEditable(false);

        btDarseBaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cajero/images/botonTriangular.png"))); // NOI18N
        btDarseBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDarseBajaActionPerformed(evt);
            }
        });

        lbIntroducir.setText("Introducir Dinero");

        lblRetirar.setText("Retirar Dinero");

        lblSaldo.setText("Mostrar Saldo");

        lblTrans.setText("Transferencia");

        lblBaja.setText("Darse de Baja");

        lblSal.setText("Saldo en la cuenta:");

        lblDestino.setText("Destino");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bSiete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bCuatro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bUno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bDos, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bTres, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(bOcho, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bCinco, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bCero, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bSeis, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bNueve, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(etInsertarBilletes)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTxtDinero, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblSal))
                                        .addGap(67, 67, 67))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextMostrarSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblDestino))
                                    .addComponent(lblIntr))
                                .addGap(50, 50, 50))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblRetirar)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblTrans)
                                                .addGap(1, 1, 1))
                                            .addComponent(lblBaja)))
                                    .addComponent(lblSaldo))
                                .addGap(20, 20, 20))
                            .addComponent(lbIntroducir, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btDarseBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btTransferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btRetirar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btIntroducir, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(etImagenInsertar)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(bTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(etImagenInsertar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(lbIntroducir)
                                .addGap(46, 46, 46)
                                .addComponent(lblRetirar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btIntroducir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btRetirar)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btSaldo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblSaldo))
                                .addGap(30, 30, 30)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblBaja)
                                .addGap(56, 56, 56)
                                .addComponent(lblTrans)
                                .addGap(22, 22, 22))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btDarseBaja)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btTransferencia))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(lblSal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextMostrarSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDestino)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblIntr)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTxtDinero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(bUno)
                        .addComponent(bDos)
                        .addComponent(bTres))
                    .addComponent(bBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bOcho)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bSeis)
                            .addComponent(bCinco)
                            .addComponent(bCuatro)
                            .addComponent(bCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(bNueve)
                                .addComponent(bSiete, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(bAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bCero)
                    .addComponent(etInsertarBilletes))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void init() {
        if (InterfazInicioSesion.mostrarVar == false) {
            this.lbIntroducir.setVisible(false);
            this.lblBaja.setVisible(false);
            this.lblIntr.setVisible(false);
            this.lblRetirar.setVisible(false);
            this.lblSaldo.setVisible(false);
            this.lblTrans.setVisible(false);
            this.jTxtDinero.setVisible(false);
            this.lblSal.setVisible(false);
            this.jTextMostrarSaldo.setVisible(false);
            this.lblDestino.setVisible(false);

            btDarseBaja.setEnabled(false);
            btIntroducir.setEnabled(false);
            btRetirar.setEnabled(false);
            btSaldo.setEnabled(false);
            btTransferencia.setEnabled(false);

        } else {
            this.lbIntroducir.setVisible(true);
            this.lblBaja.setVisible(true);
            this.lblRetirar.setVisible(true);
            this.lblSaldo.setVisible(true);
            this.lblTrans.setVisible(true);

            btDarseBaja.setEnabled(true);
            btIntroducir.setEnabled(true);
            btRetirar.setEnabled(true);
            btSaldo.setEnabled(true);
            btTransferencia.setEnabled(true);
        }
    }


    private void bTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTarjetaActionPerformed
        InterfazInicioSesion obx = new InterfazInicioSesion();
        obx.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bTarjetaActionPerformed

    String completo = "";
    String bot;

    private void bCeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCeroActionPerformed
        if (InterfazInicioSesion.mostrarVar == true) {
            bot = "0";
            completo = completo + bot;
            this.jTxtDinero.setText(completo);
        } else {
            JOptionPane.showMessageDialog(null, "Inicie sesión primero.");
        }

    }//GEN-LAST:event_bCeroActionPerformed

    private void bNueveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNueveActionPerformed
        if (InterfazInicioSesion.mostrarVar == true) {
            bot = "9";
            completo = completo + bot;
            this.jTxtDinero.setText(completo);
        } else {
            JOptionPane.showMessageDialog(null, "Inicie sesión primero.");
        }
    }//GEN-LAST:event_bNueveActionPerformed

    private void bOchoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOchoActionPerformed
        if (InterfazInicioSesion.mostrarVar == true) {
            bot = "8";
            completo = completo + bot;
            this.jTxtDinero.setText(completo);
        } else {
            JOptionPane.showMessageDialog(null, "Inicie sesión primero.");
        }
    }//GEN-LAST:event_bOchoActionPerformed

    private void bSieteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSieteActionPerformed
        if (InterfazInicioSesion.mostrarVar == true) {
            bot = "7";
            completo = completo + bot;
            this.jTxtDinero.setText(completo);
        } else {
            JOptionPane.showMessageDialog(null, "Inicie sesión primero.");
        }
    }//GEN-LAST:event_bSieteActionPerformed

    private void bSeisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSeisActionPerformed
        if (InterfazInicioSesion.mostrarVar == true) {
            bot = "6";
            completo = completo + bot;
            this.jTxtDinero.setText(completo);
        } else {
            JOptionPane.showMessageDialog(null, "Inicie sesión primero.");
        }
    }//GEN-LAST:event_bSeisActionPerformed

    private void bCincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCincoActionPerformed
        if (InterfazInicioSesion.mostrarVar == true) {
            bot = "5";
            completo = completo + bot;
            this.jTxtDinero.setText(completo);
        } else {
            JOptionPane.showMessageDialog(null, "Inicie sesión primero.");
        }
    }//GEN-LAST:event_bCincoActionPerformed

    private void bCuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCuatroActionPerformed
        if (InterfazInicioSesion.mostrarVar == true) {
            bot = "4";
            completo = completo + bot;
            this.jTxtDinero.setText(completo);
        } else {
            JOptionPane.showMessageDialog(null, "Inicie sesión primero.");
        }
    }//GEN-LAST:event_bCuatroActionPerformed

    private void bTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTresActionPerformed
        if (InterfazInicioSesion.mostrarVar == true) {
            bot = "3";
            completo = completo + bot;
            this.jTxtDinero.setText(completo);
        } else {
            JOptionPane.showMessageDialog(null, "Inicie sesión primero.");
        }
    }//GEN-LAST:event_bTresActionPerformed

    private void bDosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDosActionPerformed
        if (InterfazInicioSesion.mostrarVar == true) {
            bot = "2";
            completo = completo + bot;
            this.jTxtDinero.setText(completo);
        } else {
            JOptionPane.showMessageDialog(null, "Inicie sesión primero.");
        }
    }//GEN-LAST:event_bDosActionPerformed

    private void bUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUnoActionPerformed
        if (InterfazInicioSesion.mostrarVar == true) {
            bot = "1";
            completo = completo + bot;
            this.jTxtDinero.setText(completo);
        } else {
            JOptionPane.showMessageDialog(null, "Inicie sesión primero.");
        }
    }//GEN-LAST:event_bUnoActionPerformed

    int op;

    private void btTransferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTransferenciaActionPerformed
        op = 5;
        this.lblDestino.setVisible(true);
        this.lblSal.setVisible(false);
        this.lblIntr.setVisible(true);
        this.jTxtDinero.setVisible(true);
        this.jTextMostrarSaldo.setVisible(true);
        this.jTextMostrarSaldo.setEditable(true);
    }//GEN-LAST:event_btTransferenciaActionPerformed

    private void btSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSaldoActionPerformed
        op = 3;
        this.lblDestino.setVisible(false);
        this.lblIntr.setVisible(false);
        this.jTxtDinero.setVisible(false);
        this.lblSal.setVisible(true);
        this.jTextMostrarSaldo.setVisible(true);
        this.jTextMostrarSaldo.setEditable(false);
    }//GEN-LAST:event_btSaldoActionPerformed

    private void btRetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRetirarActionPerformed
        op = 2;
    }//GEN-LAST:event_btRetirarActionPerformed

    private void btIntroducirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIntroducirActionPerformed
        op = 1;
        this.lblDestino.setVisible(false);
        this.lblSal.setVisible(false);
        this.jTextMostrarSaldo.setVisible(false);
        this.lblIntr.setVisible(true);
        this.jTxtDinero.setVisible(true);

    }//GEN-LAST:event_btIntroducirActionPerformed

    private void btDarseBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDarseBajaActionPerformed
        op = 4;
    }//GEN-LAST:event_btDarseBajaActionPerformed

    private void bAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAceptarActionPerformed
        if (InterfazInicioSesion.mostrarVar == true) {
            switch (op) {
                case 1:
                    objControlador.insertarDinero(jTxtDinero.getText());
                    break;
                case 2:
                    objControlador.retirarDinero(jTxtDinero.getText());
                    break;
                case 3:
                    jTextMostrarSaldo.setText(objControlador.mostrarDinero());
                    break;
                case 4:
                    break;

                case 5:
                    objControlador.transferir(jTxtDinero.getText());
                    break;
                default:
                    JOptionPane.showMessageDialog(null, "Error.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Inicie sesión primero.");
        }
    }//GEN-LAST:event_bAceptarActionPerformed

    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarActionPerformed
        if (InterfazInicioSesion.mostrarVar == true) {
        } else {
            JOptionPane.showMessageDialog(null, "Inicie sesión primero.");
        }
    }//GEN-LAST:event_bCancelarActionPerformed

    private void bBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBorrarActionPerformed
        if (InterfazInicioSesion.mostrarVar == true) {
            this.jTextMostrarSaldo.setText("");
            this.jTxtDinero.setText("");
            completo = "";
            bot = "";
        } else {
            JOptionPane.showMessageDialog(null, "Inicie sesión primero.");
        }
    }//GEN-LAST:event_bBorrarActionPerformed

    private void conexionBD() {
        objControlador.conexionBD();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazCajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazCajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazCajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazCajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazCajero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAceptar;
    private javax.swing.JButton bBorrar;
    private javax.swing.JButton bCancelar;
    private javax.swing.JButton bCero;
    private javax.swing.JButton bCinco;
    private javax.swing.JButton bCuatro;
    private javax.swing.JButton bDos;
    private javax.swing.JButton bNueve;
    private javax.swing.JButton bOcho;
    private javax.swing.JButton bSeis;
    private javax.swing.JButton bSiete;
    private javax.swing.JButton bTarjeta;
    private javax.swing.JButton bTres;
    private javax.swing.JButton bUno;
    private javax.swing.JButton btDarseBaja;
    private javax.swing.JButton btIntroducir;
    private javax.swing.JButton btRetirar;
    private javax.swing.JButton btSaldo;
    private javax.swing.JButton btTransferencia;
    private javax.swing.JLabel etImagenInsertar;
    private javax.swing.JLabel etInsertarBilletes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextMostrarSaldo;
    private javax.swing.JTextField jTxtDinero;
    private javax.swing.JLabel lbIntroducir;
    private javax.swing.JLabel lblBaja;
    private javax.swing.JLabel lblDestino;
    private javax.swing.JLabel lblIntr;
    private javax.swing.JLabel lblRetirar;
    private javax.swing.JLabel lblSal;
    private javax.swing.JLabel lblSaldo;
    private javax.swing.JLabel lblTrans;
    // End of variables declaration//GEN-END:variables
}
