/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cajero.vista;

import com.cajero.controlador.Controlador;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.io.File;
import javax.swing.*;

/**
 *
 * @author David
 */
public class InterfazCajero extends javax.swing.JFrame {

    Controlador objControlador = new Controlador();
    Icon iconGato = new javax.swing.ImageIcon((new File("src/com/cajero/images/gato.png")).getAbsolutePath());

    /**
     * Creates new form InterfazCajero
     */
    public InterfazCajero() {
        initComponents();
        conexionBD();
        setLocationRelativeTo(null);
        init();
        usuarios.setModel(new DefaultComboBoxModel(objControlador.usuarios().toArray()));
        paint(this.getGraphics());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etImagenInsertar = new javax.swing.JLabel();
        bTarjeta = new javax.swing.JButton();
        bCancelar = new javax.swing.JButton();
        bBorrar = new javax.swing.JButton();
        etInsertarBilletes = new javax.swing.JLabel();
        bAceptar = new javax.swing.JButton();
        bUno = new javax.swing.JButton();
        bDos = new javax.swing.JButton();
        bTres = new javax.swing.JButton();
        bCuatro = new javax.swing.JButton();
        bSiete = new javax.swing.JButton();
        bCinco = new javax.swing.JButton();
        bSeis = new javax.swing.JButton();
        bOcho = new javax.swing.JButton();
        bCero = new javax.swing.JButton();
        bNueve = new javax.swing.JButton();
        jTxtDinero = new javax.swing.JTextField();
        lblIntr = new javax.swing.JLabel();
        btIntroducir = new javax.swing.JButton();
        btRetirar = new javax.swing.JButton();
        btSaldo = new javax.swing.JButton();
        btTransferencia = new javax.swing.JButton();
        JTextMostrarSaldo = new javax.swing.JTextField();
        btDarseBaja = new javax.swing.JButton();
        lbIntroducir = new javax.swing.JLabel();
        lblRetirar = new javax.swing.JLabel();
        lblSaldo = new javax.swing.JLabel();
        lblTrans = new javax.swing.JLabel();
        lblBaja = new javax.swing.JLabel();
        lblSal = new javax.swing.JLabel();
        lblDestino = new javax.swing.JLabel();
        operacion = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        logout = new javax.swing.JButton();
        usuarios = new javax.swing.JComboBox<>();
        btUltOpr = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        etImagenInsertar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cajero/images/imagenInsertar.png"))); // NOI18N

        bTarjeta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cajero/images/imagenTarjeta.png"))); // NOI18N
        bTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTarjetaActionPerformed(evt);
            }
        });

        bCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cajero/images/botonCancelar.png"))); // NOI18N
        bCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarActionPerformed(evt);
            }
        });

        bBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cajero/images/botonBorrar.png"))); // NOI18N
        bBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBorrarActionPerformed(evt);
            }
        });

        etInsertarBilletes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cajero/images/imagenBilletes.png"))); // NOI18N

        bAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cajero/images/botonAceptar.png"))); // NOI18N
        bAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAceptarActionPerformed(evt);
            }
        });

        bUno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cajero/images/unoBoton.png"))); // NOI18N
        bUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUnoActionPerformed(evt);
            }
        });

        bDos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cajero/images/dosBoton.png"))); // NOI18N
        bDos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDosActionPerformed(evt);
            }
        });

        bTres.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cajero/images/tresBoton.png"))); // NOI18N
        bTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTresActionPerformed(evt);
            }
        });

        bCuatro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cajero/images/cuatroBoton.png"))); // NOI18N
        bCuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCuatroActionPerformed(evt);
            }
        });

        bSiete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cajero/images/sieteBoton.png"))); // NOI18N
        bSiete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSieteActionPerformed(evt);
            }
        });

        bCinco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cajero/images/cincoBoton.png"))); // NOI18N
        bCinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCincoActionPerformed(evt);
            }
        });

        bSeis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cajero/images/seisBoton.png"))); // NOI18N
        bSeis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSeisActionPerformed(evt);
            }
        });

        bOcho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cajero/images/ochoBoton.png"))); // NOI18N
        bOcho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOchoActionPerformed(evt);
            }
        });

        bCero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cajero/images/ceroBoton.png"))); // NOI18N
        bCero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCeroActionPerformed(evt);
            }
        });

        bNueve.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cajero/images/nueveBoton.png"))); // NOI18N
        bNueve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNueveActionPerformed(evt);
            }
        });

        jTxtDinero.setEditable(false);

        lblIntr.setText("Inserta la cantidad:");

        btIntroducir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cajero/images/botonTriangular.png"))); // NOI18N
        btIntroducir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIntroducirActionPerformed(evt);
            }
        });

        btRetirar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cajero/images/botonTriangular.png"))); // NOI18N
        btRetirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRetirarActionPerformed(evt);
            }
        });

        btSaldo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cajero/images/botonTriangular.png"))); // NOI18N
        btSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSaldoActionPerformed(evt);
            }
        });

        btTransferencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cajero/images/botonTriangular.png"))); // NOI18N
        btTransferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTransferenciaActionPerformed(evt);
            }
        });

        JTextMostrarSaldo.setEditable(false);

        btDarseBaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cajero/images/botonTriangular.png"))); // NOI18N
        btDarseBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDarseBajaActionPerformed(evt);
            }
        });

        lbIntroducir.setText("Introducir Dinero");

        lblRetirar.setText("Retirar Dinero");

        lblSaldo.setText("Mostrar Saldo");

        lblTrans.setText("Transferencia");

        lblBaja.setText("Darse de Baja");

        lblSal.setText("Saldo en la cuenta:");

        lblDestino.setText("Destino");

        operacion.setText("Bienvenido a Kay&Ve bank!");

        logout.setText("Retirar tarj.");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        usuarios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btUltOpr.setText("Operaciones");
        btUltOpr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUltOprActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bSiete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bCuatro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bUno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bDos, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bTres, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(bOcho, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bCinco, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bCero, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bSeis, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bNueve, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(bBorrar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(etInsertarBilletes))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jTxtDinero, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lblSal)
                                                    .addComponent(JTextMostrarSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lblIntr))
                                                .addGap(117, 117, 117))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(lblDestino)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(usuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblRetirar)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(1, 1, 1)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addComponent(lblTrans)
                                                                .addGap(1, 1, 1))
                                                            .addComponent(lblBaja)))
                                                    .addComponent(lblSaldo))
                                                .addGap(20, 20, 20))
                                            .addComponent(lbIntroducir, javax.swing.GroupLayout.Alignment.TRAILING)))
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(operacion, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btDarseBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btTransferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btRetirar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btIntroducir, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(etImagenInsertar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(bTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18))
                            .addComponent(btUltOpr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(operacion, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(51, 51, 51)
                                        .addComponent(lbIntroducir)
                                        .addGap(46, 46, 46)
                                        .addComponent(lblRetirar)
                                        .addGap(46, 46, 46)
                                        .addComponent(lblSaldo)
                                        .addGap(30, 30, 30)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(36, 36, 36)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(90, 90, 90)
                                                .addComponent(lblSal)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(JTextMostrarSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblIntr)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTxtDinero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblBaja)
                                        .addGap(56, 56, 56))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lblDestino)
                                            .addComponent(usuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(43, 43, 43)))
                                .addComponent(lblTrans))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(btUltOpr)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(etImagenInsertar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(logout))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(btIntroducir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btRetirar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btSaldo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btDarseBaja)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btTransferencia)))
                        .addGap(44, 44, 44)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(bUno)
                        .addComponent(bDos)
                        .addComponent(bTres))
                    .addComponent(bBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bOcho)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bSeis)
                            .addComponent(bCinco)
                            .addComponent(bCuatro)
                            .addComponent(bCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(bNueve)
                                .addComponent(bSiete, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(bAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bCero)
                    .addComponent(etInsertarBilletes))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    Graphics g;

    @Override
    public void paint(Graphics g) {
        super.paint(g); //To change body of generated methods, choose Tools | Templates.
        Graphics2D g2 = (Graphics2D) g;
        g2.drawRect(50, 40, 470, 345);
    }

    public void init() {
        if (InterfazInicioSesion.mostrarVar == false) {
            this.lbIntroducir.setVisible(false);
            this.lblBaja.setVisible(false);
            this.lblRetirar.setVisible(false);
            this.lblSaldo.setVisible(false);
            this.lblTrans.setVisible(false);

            this.lblIntr.setVisible(false);
            this.jTxtDinero.setVisible(false);
            this.lblSal.setVisible(false);
            this.JTextMostrarSaldo.setVisible(false);
            this.lblDestino.setVisible(false);
            this.usuarios.setVisible(false);

            btDarseBaja.setEnabled(false);
            btIntroducir.setEnabled(false);
            btRetirar.setEnabled(false);
            btSaldo.setEnabled(false);
            btTransferencia.setEnabled(false);
            btUltOpr.setVisible(false);
            logout.setVisible(false);

        } else {
            this.lbIntroducir.setVisible(true);
            this.lblBaja.setVisible(true);
            this.lblRetirar.setVisible(true);
            this.lblSaldo.setVisible(true);
            this.lblTrans.setVisible(true);

            btDarseBaja.setEnabled(true);
            btIntroducir.setEnabled(true);
            btRetirar.setEnabled(true);
            btSaldo.setEnabled(true);
            btTransferencia.setEnabled(true);
            btUltOpr.setVisible(true);
            logout.setVisible(true);
        }
    }


    private void bTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTarjetaActionPerformed

        if (InterfazInicioSesion.mostrarVar == true) {
            JOptionPane.showMessageDialog(null, "Ya has iniciado sesión.");
        } else {
            InterfazInicioSesion obx = new InterfazInicioSesion();
            obx.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_bTarjetaActionPerformed

    String completo = "";
    String bot;

    private void bCeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCeroActionPerformed
        if (InterfazInicioSesion.mostrarVar == true) {
            if (op != 0) {
                bot = "0";
                completo = completo + bot;
                this.jTxtDinero.setText(completo);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Inicie sesión primero.");
        }

    }//GEN-LAST:event_bCeroActionPerformed

    private void bNueveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNueveActionPerformed
        if (InterfazInicioSesion.mostrarVar == true) {
            if (op != 0) {
                bot = "9";
                completo = completo + bot;
                this.jTxtDinero.setText(completo);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Inicie sesión primero.");
        }
    }//GEN-LAST:event_bNueveActionPerformed

    private void bOchoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOchoActionPerformed
        if (InterfazInicioSesion.mostrarVar == true) {
            if (op != 0) {
                bot = "8";
                completo = completo + bot;
                this.jTxtDinero.setText(completo);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Inicie sesión primero.");
        }
    }//GEN-LAST:event_bOchoActionPerformed

    private void bSieteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSieteActionPerformed
        if (InterfazInicioSesion.mostrarVar == true) {
            if (op != 0) {
                bot = "7";
                completo = completo + bot;
                this.jTxtDinero.setText(completo);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Inicie sesión primero.");
        }
    }//GEN-LAST:event_bSieteActionPerformed

    private void bSeisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSeisActionPerformed
        if (InterfazInicioSesion.mostrarVar == true) {
            if (op != 0) {
                bot = "6";
                completo = completo + bot;
                this.jTxtDinero.setText(completo);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Inicie sesión primero.");
        }
    }//GEN-LAST:event_bSeisActionPerformed

    private void bCincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCincoActionPerformed
        if (InterfazInicioSesion.mostrarVar == true) {
            if (op != 0) {
                bot = "5";
                completo = completo + bot;
                this.jTxtDinero.setText(completo);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Inicie sesión primero.");
        }
    }//GEN-LAST:event_bCincoActionPerformed

    private void bCuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCuatroActionPerformed
        if (InterfazInicioSesion.mostrarVar == true) {
            if (op != 0) {
                bot = "4";
                completo = completo + bot;
                this.jTxtDinero.setText(completo);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Inicie sesión primero.");
        }
    }//GEN-LAST:event_bCuatroActionPerformed

    private void bTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTresActionPerformed
        if (InterfazInicioSesion.mostrarVar == true) {
            if (op != 0) {
                bot = "3";
                completo = completo + bot;
                this.jTxtDinero.setText(completo);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Inicie sesión primero.");
        }
    }//GEN-LAST:event_bTresActionPerformed

    private void bDosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDosActionPerformed
        if (InterfazInicioSesion.mostrarVar == true) {
            if (op != 0) {
                bot = "2";
                completo = completo + bot;
                this.jTxtDinero.setText(completo);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Inicie sesión primero.");
        }
    }//GEN-LAST:event_bDosActionPerformed

    private void bUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUnoActionPerformed
        if (InterfazInicioSesion.mostrarVar == true) {
            if (op != 0) {
                bot = "1";
                completo = completo + bot;
                this.jTxtDinero.setText(completo);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Inicie sesión primero.");
        }
    }//GEN-LAST:event_bUnoActionPerformed

    int op = 0;

    private void btTransferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTransferenciaActionPerformed
        repaint();
        if (op == 0) {
            operacion.setText("Operación: Transferencia bancaria.");
            op = 5;
            this.lblDestino.setVisible(true);
            this.lblSal.setVisible(false);
            this.lblIntr.setVisible(true);
            this.jTxtDinero.setVisible(true);
            this.usuarios.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Ya hay otra operación en curso.");
        }

    }//GEN-LAST:event_btTransferenciaActionPerformed

    private void btSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSaldoActionPerformed
        repaint();
        if (op == 0) {
            operacion.setText("Operación: Mostrar saldo.");
            op = 3;
            this.lblDestino.setVisible(false);
            this.lblIntr.setVisible(false);
            this.jTxtDinero.setVisible(false);
            this.lblSal.setVisible(true);
            this.JTextMostrarSaldo.setVisible(true);
            this.JTextMostrarSaldo.setEditable(false);
        } else {
            JOptionPane.showMessageDialog(null, "Ya hay otra operación en curso.");
        }


    }//GEN-LAST:event_btSaldoActionPerformed

    private void btRetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRetirarActionPerformed
        repaint();
        if (op == 0) {
            operacion.setText("Operación: Retirar dinero.");
            op = 2;
            this.lblDestino.setVisible(false);
            this.lblSal.setVisible(false);
            this.JTextMostrarSaldo.setVisible(false);
            this.lblIntr.setVisible(true);
            this.jTxtDinero.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Ya hay otra operación en curso.");
        }


    }//GEN-LAST:event_btRetirarActionPerformed

    private void btIntroducirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIntroducirActionPerformed
        repaint();
        if (op == 0) {
            operacion.setText("Operación: Ingresar dinero.");
            op = 1;
            this.lblDestino.setVisible(false);
            this.lblSal.setVisible(false);
            this.JTextMostrarSaldo.setVisible(false);
            this.lblIntr.setVisible(true);
            this.jTxtDinero.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Ya hay otra operación en curso.");
        }


    }//GEN-LAST:event_btIntroducirActionPerformed

    private void btDarseBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDarseBajaActionPerformed
        repaint();
        if (op == 0) {
            operacion.setText("Operación: Darse de baja.");
            op = 4;
        } else {
            JOptionPane.showMessageDialog(null, "Ya hay otra operación en curso.");
        }
    }//GEN-LAST:event_btDarseBajaActionPerformed

    public void reset() {
        operacion.setText("Bienvenido a Kay&Ve bank!");
        this.lblIntr.setVisible(false);
        this.jTxtDinero.setVisible(false);
        this.lblSal.setVisible(false);
        this.JTextMostrarSaldo.setVisible(false);
        this.lblDestino.setVisible(false);
        this.jTxtDinero.setText("");
        this.JTextMostrarSaldo.setText("");
        this.usuarios.setVisible(false);
        bot = "";
        completo = "";
        op = 0;
    }


    private void bAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAceptarActionPerformed
        repaint();
        if (InterfazInicioSesion.mostrarVar == true) {
            switch (op) {
                case 0:
                    reset();
                    break;
                case 1:
                    if (!jTxtDinero.getText().isEmpty()) {
                        objControlador.insertarDinero(jTxtDinero.getText());
                    } else {
                        JOptionPane.showMessageDialog(null, "Inserte una cantidad.");
                    }
                    reset();
                    break;

                case 2:
                    if (!jTxtDinero.getText().isEmpty()) {
                        objControlador.retirarDinero(jTxtDinero.getText());
                    } else {
                        JOptionPane.showMessageDialog(null, "Inserte una cantidad.");
                    }
                    reset();
                    break;

                case 3:
                    JTextMostrarSaldo.setText(objControlador.mostrarDinero());
                    break;

                case 4:
                    if (JOptionPane.showConfirmDialog(null, "Estás seguro de que quieres borrar la cuenta?", "ATENCIÓN",
                            JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                        objControlador.darseDeBaja();
                        InterfazInicioSesion.mostrarVar = false;
                        operacion.setText("Bienvenido a Kay&Ve bank!");
                        init();
                        this.logout.setVisible(false);
                        repaint();
                    } else {
                        JOptionPane.showConfirmDialog(null, iconGato, "Nos alegramos de que te quedes!", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
                        reset();
                    }
                    break;

                case 5:
                    objControlador.transferir(jTxtDinero.getText(), String.valueOf(usuarios.getSelectedItem()));
                    reset();
                    repaint();
                    break;

                default:
                    JOptionPane.showMessageDialog(null, "Error.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Inicie sesión primero.");
        }
        repaint();
    }//GEN-LAST:event_bAceptarActionPerformed

    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarActionPerformed
        repaint();
        if (InterfazInicioSesion.mostrarVar == true) {
            reset();
        } else {
            JOptionPane.showMessageDialog(null, "Inicie sesión primero.");
        }
    }//GEN-LAST:event_bCancelarActionPerformed

    private void bBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBorrarActionPerformed
        repaint();
        if (InterfazInicioSesion.mostrarVar == true) {
            this.JTextMostrarSaldo.setText("");
            this.jTxtDinero.setText("");
            completo = "";
            bot = "";
        } else {
            JOptionPane.showMessageDialog(null, "Inicie sesión primero.");
        }
    }//GEN-LAST:event_bBorrarActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        InterfazInicioSesion.mostrarVar = false;
        operacion.setText("Bienvenido a Kay&Ve bank!");
        init();
        this.logout.setVisible(false);
        repaint();
    }//GEN-LAST:event_logoutActionPerformed

    private void btUltOprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUltOprActionPerformed

        class TablaOP extends JFrame {

            public TablaOP() {

                setLocationRelativeTo(null);

                setSize(650, 300);
                JTable tabla = new JTable();

                tabla.setModel(objControlador.botonMostrarOperaciones());

                add(tabla);
                setVisible(true);
            }
        }

        TablaOP t = new TablaOP();
        t.setVisible(true);

    }//GEN-LAST:event_btUltOprActionPerformed

    private void conexionBD() {
        objControlador.conexionBD();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazCajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazCajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazCajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazCajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazCajero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JTextMostrarSaldo;
    private javax.swing.JButton bAceptar;
    private javax.swing.JButton bBorrar;
    private javax.swing.JButton bCancelar;
    private javax.swing.JButton bCero;
    private javax.swing.JButton bCinco;
    private javax.swing.JButton bCuatro;
    private javax.swing.JButton bDos;
    private javax.swing.JButton bNueve;
    private javax.swing.JButton bOcho;
    private javax.swing.JButton bSeis;
    private javax.swing.JButton bSiete;
    private javax.swing.JButton bTarjeta;
    private javax.swing.JButton bTres;
    private javax.swing.JButton bUno;
    private javax.swing.JButton btDarseBaja;
    private javax.swing.JButton btIntroducir;
    private javax.swing.JButton btRetirar;
    private javax.swing.JButton btSaldo;
    private javax.swing.JButton btTransferencia;
    private javax.swing.JButton btUltOpr;
    private javax.swing.JLabel etImagenInsertar;
    private javax.swing.JLabel etInsertarBilletes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTxtDinero;
    private javax.swing.JLabel lbIntroducir;
    private javax.swing.JLabel lblBaja;
    private javax.swing.JLabel lblDestino;
    private javax.swing.JLabel lblIntr;
    private javax.swing.JLabel lblRetirar;
    private javax.swing.JLabel lblSal;
    private javax.swing.JLabel lblSaldo;
    private javax.swing.JLabel lblTrans;
    private javax.swing.JButton logout;
    private javax.swing.JLabel operacion;
    private javax.swing.JComboBox<String> usuarios;
    // End of variables declaration//GEN-END:variables
}
